name: manga_verse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  salomon_bottom_bar: 3.2.0
  http: 0.13.6
  cached_network_image: 3.2.3
  pull_to_refresh: 2.0.0
  google_fonts: 4.0.3
  expandable: 5.0.1
  animated_text_kit: 4.2.2
  infinite_scroll_pagination: 3.2.0
  loading_animation_widget: 1.2.0+4
  fluttertoast: 8.2.2
  delayed_display: 2.0.0
  flutter_native_splash: 2.3.1
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/images/launcher.png
  ios: true
  min_sdk_android: 21

flutter_native_splash: 
  android: true
  ios: true
  web: true
  image: "assets/images/launcher.png"
  color: "#F9F5F6"
